#!/usr/bin/env node
/**
 * OPAIJA Studios — Interactive Setup Script
 * Run: node scripts/setup.js
 *
 * Creates your .env file with all required API keys.
 * Claude Desktop can run this automatically when it detects .env is missing.
 */

import { createInterface } from "readline";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ENV_PATH = join(ROOT, ".env");

const GREEN  = "\x1b[32m";
const YELLOW = "\x1b[33m";
const CYAN   = "\x1b[36m";
const DIM    = "\x1b[2m";
const RESET  = "\x1b[0m";
const BOLD   = "\x1b[1m";

function log(msg)  { console.log(msg); }
function ok(msg)   { console.log(`${GREEN}✓${RESET} ${msg}`); }
function tip(msg)  { console.log(`${CYAN}→${RESET} ${DIM}${msg}${RESET}`); }
function warn(msg) { console.log(`${YELLOW}!${RESET} ${msg}`); }

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((resolve) => rl.question(q, resolve));

function parseExistingEnv() {
  if (!existsSync(ENV_PATH)) return {};
  const lines = readFileSync(ENV_PATH, "utf8").split("\n");
  const vals = {};
  for (const line of lines) {
    const match = line.match(/^([A-Z_]+)=(.*)$/);
    if (match) vals[match[1]] = match[2];
  }
  return vals;
}

async function main() {
  log(`\n${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}`);
  log(`${BOLD}  OPAIJA Studios — Environment Setup${RESET}`);
  log(`${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n`);

  const existing = parseExistingEnv();
  const isUpdate = Object.keys(existing).length > 0;

  if (isUpdate) {
    warn(".env already exists. Press Enter to keep current values, or type a new one.\n");
  } else {
    log("This will create your .env file with your API keys.\n");
    log(`${DIM}Keys are stored locally only — never committed to GitHub.${RESET}\n`);
  }

  const def = (key) => existing[key] ? ` ${DIM}[${existing[key].slice(0, 8)}...]${RESET}` : "";

  // FAL
  log(`${BOLD}1. FAL.AI (Seedance 2.0 Video Generation)${RESET}`);
  tip("Get your key at: fal.ai/dashboard → API Keys");
  const FAL_KEY = (await ask(`   FAL_KEY${def("FAL_KEY")}: `)).trim() || existing["FAL_KEY"] || "";
  log("");

  // Anthropic
  log(`${BOLD}2. Anthropic (Claude AI — Script Writing & QA)${RESET}`);
  tip("Get your key at: console.anthropic.com → API Keys");
  const ANTHROPIC_API_KEY = (await ask(`   ANTHROPIC_API_KEY${def("ANTHROPIC_API_KEY")}: `)).trim() || existing["ANTHROPIC_API_KEY"] || "";
  log("");

  // ElevenLabs
  log(`${BOLD}3. ElevenLabs (The Web-Teller Narrator Voice)${RESET}`);
  tip("Get your key at: elevenlabs.io → Profile → API Key");
  const ELEVENLABS_API_KEY = (await ask(`   ELEVENLABS_API_KEY${def("ELEVENLABS_API_KEY")}: `)).trim() || existing["ELEVENLABS_API_KEY"] || "";
  let ELEVENLABS_VOICE_ID_WEB_TELLER = existing["ELEVENLABS_VOICE_ID_WEB_TELLER"] || "";
  if (ELEVENLABS_API_KEY) {
    tip("In ElevenLabs, go to Voice Library → find your narrator voice → copy the Voice ID");
    ELEVENLABS_VOICE_ID_WEB_TELLER = (await ask(`   ELEVENLABS_VOICE_ID_WEB_TELLER${def("ELEVENLABS_VOICE_ID_WEB_TELLER")}: `)).trim() || ELEVENLABS_VOICE_ID_WEB_TELLER;
  }
  log("");

  // Resend (optional)
  log(`${BOLD}4. Resend (Fan Email List) ${DIM}— Optional${RESET}`);
  tip("Get your key at: resend.com → API Keys");
  const RESEND_API_KEY = (await ask(`   RESEND_API_KEY${def("RESEND_API_KEY")} (Enter to skip): `)).trim() || existing["RESEND_API_KEY"] || "";
  let RESEND_FROM_EMAIL = existing["RESEND_FROM_EMAIL"] || "";
  let RESEND_AUDIENCE_ID = existing["RESEND_AUDIENCE_ID"] || "";
  if (RESEND_API_KEY) {
    RESEND_FROM_EMAIL = (await ask(`   RESEND_FROM_EMAIL (e.g. noreply@opaija.com): `)).trim() || RESEND_FROM_EMAIL;
    RESEND_AUDIENCE_ID = (await ask(`   RESEND_AUDIENCE_ID${def("RESEND_AUDIENCE_ID")}: `)).trim() || RESEND_AUDIENCE_ID;
  }
  log("");

  // Printful (optional)
  log(`${BOLD}5. Printful (Merch / Print-on-Demand) ${DIM}— Optional${RESET}`);
  const PRINTFUL_API_KEY = (await ask(`   PRINTFUL_API_KEY${def("PRINTFUL_API_KEY")} (Enter to skip): `)).trim() || existing["PRINTFUL_API_KEY"] || "";
  log("");

  // Write .env
  const envContent = [
    "# OPAIJA Studios — Environment Variables",
    "# Generated by: node scripts/setup.js",
    "# NEVER commit this file to git.",
    "",
    "# ── VIDEO GENERATION (fal.ai — Seedance 2.0) ─────────────────",
    `FAL_KEY=${FAL_KEY}`,
    "VIDEO_PROVIDER=fal",
    "",
    "# ── AI BRAIN (Claude) ─────────────────────────────────────────",
    `ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}`,
    "",
    "# ── VOICE / NARRATION ─────────────────────────────────────────",
    `ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}`,
    `ELEVENLABS_VOICE_ID_WEB_TELLER=${ELEVENLABS_VOICE_ID_WEB_TELLER}`,
    "",
    "# ── EMAIL / GROWTH ────────────────────────────────────────────",
    `RESEND_API_KEY=${RESEND_API_KEY}`,
    `RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}`,
    `RESEND_AUDIENCE_ID=${RESEND_AUDIENCE_ID}`,
    "",
    "# ── MERCH ─────────────────────────────────────────────────────",
    `PRINTFUL_API_KEY=${PRINTFUL_API_KEY}`,
    "",
    "# ── SERVER ────────────────────────────────────────────────────",
    "PORT=8787",
    "PUBLIC_SITE_URL=http://localhost:8787",
    "",
  ].join("\n");

  writeFileSync(ENV_PATH, envContent, "utf8");

  log(`${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}`);
  ok(`.env ${isUpdate ? "updated" : "created"} successfully\n`);

  // Summary
  const checks = [
    { label: "FAL_KEY (Seedance video)",        ok: Boolean(FAL_KEY) },
    { label: "ANTHROPIC_API_KEY (Claude AI)",   ok: Boolean(ANTHROPIC_API_KEY) },
    { label: "ELEVENLABS_API_KEY (narration)",  ok: Boolean(ELEVENLABS_API_KEY) },
    { label: "RESEND_API_KEY (email list)",     ok: Boolean(RESEND_API_KEY) },
    { label: "PRINTFUL_API_KEY (merch)",        ok: Boolean(PRINTFUL_API_KEY) },
  ];

  log("Services configured:\n");
  for (const check of checks) {
    if (check.ok) {
      ok(check.label);
    } else {
      log(`${DIM}○ ${check.label} — not set (dry-run mode)${RESET}`);
    }
  }

  log(`\n${BOLD}Next step:${RESET}`);
  log(`  npm run dev\n`);
  log(`${BOLD}Then open:${RESET}`);
  log(`  http://localhost:8787/command\n`);
  log(`${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}\n`);

  rl.close();
}

main().catch((err) => {
  console.error("Setup failed:", err.message);
  process.exit(1);
});
